name: Deploy aws
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # JDK setting - github actions에서 사용할 JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # MAVEN build
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # docker build & push to production
      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/springboot-demo .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-demo

      # docker build & push to develop
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ap-northeast-2
          application_name: api-docker-app-eb
          environment_name: Api-docker-app-eb-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-211125346644
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

